//! Tool-call parsers.
//!
//! Ported from every concrete parser in `mlx-lm`'s `mlx_lm/tool_parsers/`
//! (`json_tools`, `pythonic`, `mistral`, `qwen3_coder`, `glm47`, `kimi_k2`,
//! `longcat`, `minimax_m2`, `function_gemma`, `gemma4`) plus the
//! `_infer_tool_parser` selector in `mlx_lm/tokenizer_utils.py` (~548+).
//! Cross-referenced against `mlx-swift-lm`'s `MLXLMCommon/Tool/*`
//! (`ToolCall`, `ToolCallFormat`, `ToolCallProcessor`, `Value`, `Parsers`)
//! for the abstraction shape: a `ToolParser` trait producing structured
//! `ToolCall`s, selected by chat-template content.
//!
//! Python `ast.literal_eval` is approximated with a JSON-first parse and a
//! conservative Python-literal fallback (`True`/`False`/`None`, single-quoted
//! strings); values that fail both are kept as the original string, matching
//! the Python parsers' "keep as string" behavior.

use serde_json::Value;

use crate::Error;

// Constant marker + ordered selection dispatch table, regenerated by
// `cargo xtask-codegen` from `mlxrs/data/tokenizer/tool_parsers.toml`
// (single source of truth; mlx-lm df1d3f3) into the committed
// `crate::tokenizer::generated` module. Parser *logic* below stays Rust and
// consumes this table instead of inline string literals.
use crate::tokenizer::generated::{TOOL_PARSER_MARKERS, TOOL_PARSER_SELECT};

/// `tool_call_start` for `name` from the generated table.
fn marker_start(name: &str) -> &'static str {
  TOOL_PARSER_MARKERS
    .iter()
    .find(|m| m.name == name)
    .map(|m| m.start)
    .unwrap_or("")
}

/// `tool_call_end` for `name` from the generated table.
fn marker_end(name: &str) -> &'static str {
  TOOL_PARSER_MARKERS
    .iter()
    .find(|m| m.name == name)
    .map(|m| m.end)
    .unwrap_or("")
}

/// A single parsed tool call (Swift `ToolCall` shape: name + arguments,
/// optional id for kimi-style calls).
#[derive(Debug, Clone, PartialEq)]
pub struct ToolCall {
  /// Function name.
  pub name: String,
  /// Arguments as a JSON object (or other JSON value for raw payloads).
  pub arguments: Value,
  /// Optional tool-call id (kimi_k2 emits `functions.name:idx`).
  pub id: Option<String>,
}

impl ToolCall {
  fn new(name: impl Into<String>, arguments: Value) -> Self {
    Self {
      name: name.into(),
      arguments,
      id: None,
    }
  }
}

/// A tool-call parser (Python `tool_module.parse_tool_call`). Implementors
/// also expose the `tool_call_start` / `tool_call_end` delimiters.
pub trait ToolParser: Send + Sync {
  /// Parse one assistant tool-call payload into one or more [`ToolCall`]s.
  fn parse(&self, text: &str, tools: Option<&Value>) -> Result<Vec<ToolCall>, Error>;

  /// The stable parser name (matches the Python module name).
  fn name(&self) -> &'static str;

  /// The `tool_call_start` delimiter, looked up from the marker table
  /// regenerated by `cargo xtask-codegen` from
  /// `mlxrs/data/tokenizer/tool_parsers.toml` into the committed
  /// `mlxrs/src/tokenizer/generated.rs`.
  fn tool_call_start(&self) -> &'static str {
    marker_start(self.name())
  }

  /// The `tool_call_end` delimiter, from the generated marker table.
  fn tool_call_end(&self) -> &'static str {
    marker_end(self.name())
  }
}

fn err(msg: impl Into<String>) -> Error {
  Error::tokenizer(msg.into())
}

/// Approximates Python `ast.literal_eval` enough for tool-arg coercion:
/// JSON first, then `True`/`False`/`None`, single-quoted strings, and bare
/// ints/floats. Falls back to returning the input as a JSON string.
fn literal_eval(s: &str) -> Value {
  let t = s.trim();
  if let Ok(v) = serde_json::from_str::<Value>(t) {
    return v;
  }
  match t {
    "True" | "true" => return Value::Bool(true),
    "False" | "false" => return Value::Bool(false),
    "None" | "null" => return Value::Null,
    _ => {}
  }
  if (t.starts_with('\'') && t.ends_with('\'') && t.len() >= 2)
    || (t.starts_with('"') && t.ends_with('"') && t.len() >= 2)
  {
    return Value::String(t[1..t.len() - 1].to_owned());
  }
  if let Ok(i) = t.parse::<i64>() {
    return Value::Number(i.into());
  }
  if let Ok(f) = t.parse::<f64>()
    && let Some(n) = serde_json::Number::from_f64(f)
  {
    return Value::Number(n);
  }
  // Python-list/tuple/dict-ish: try swapping single quotes to double quotes.
  if (t.starts_with('[') && t.ends_with(']'))
    || (t.starts_with('{') && t.ends_with('}'))
    || (t.starts_with('(') && t.ends_with(')'))
  {
    let swapped = t
      .replace('\'', "\"")
      .replace("(", "[")
      .replace(")", "]")
      .replace("True", "true")
      .replace("False", "false")
      .replace("None", "null");
    if let Ok(v) = serde_json::from_str::<Value>(&swapped) {
      return v;
    }
  }
  Value::String(t.to_owned())
}

/// JSON-then-literal deserialize (Python `_deserialize` in glm47/longcat/kimi).
fn deserialize(value: &str) -> Value {
  if let Ok(v) = serde_json::from_str::<Value>(value) {
    return v;
  }
  literal_eval(value)
}

fn obj(name: &str, args: Value) -> Vec<ToolCall> {
  vec![ToolCall::new(name, args)]
}

fn tool_properties<'a>(
  tools: Option<&'a Value>,
  func_name: &str,
) -> Option<&'a serde_json::Map<String, Value>> {
  let arr = tools?.as_array()?;
  for tool in arr {
    let f = tool.get("function")?;
    if f.get("name").and_then(Value::as_str) == Some(func_name) {
      return f
        .get("parameters")
        .and_then(|p| p.get("properties"))
        .and_then(Value::as_object);
    }
  }
  None
}

fn string_arg_names(tools: Option<&Value>, func_name: &str) -> Vec<String> {
  tool_properties(tools, func_name)
    .map(|props| {
      props
        .iter()
        .filter(|(_, v)| v.get("type").and_then(Value::as_str) == Some("string"))
        .map(|(k, _)| k.clone())
        .collect()
    })
    .unwrap_or_default()
}

// ----------------------------------------------------------------------------
// json_tools
// ----------------------------------------------------------------------------

/// `json_tools` — `<tool_call>{json}</tool_call>`; the payload is plain JSON.
pub struct JsonTools;

impl ToolParser for JsonTools {
  fn parse(&self, text: &str, _tools: Option<&Value>) -> Result<Vec<ToolCall>, Error> {
    let v: Value =
      serde_json::from_str(text.trim()).map_err(|e| err(format!("json_tools: {e}")))?;
    let name = v
      .get("name")
      .and_then(Value::as_str)
      .ok_or_else(|| err("json_tools: missing name"))?;
    let args = v.get("arguments").cloned().unwrap_or(Value::Null);
    Ok(obj(name, args))
  }
  fn name(&self) -> &'static str {
    "json_tools"
  }
}

// ----------------------------------------------------------------------------
// pythonic: [func(arg="v", n=2)]
// ----------------------------------------------------------------------------

/// `pythonic` — `<|tool_call_start|>[name(a="x", b=2)]<|tool_call_end|>`.
pub struct Pythonic;

impl ToolParser for Pythonic {
  fn parse(&self, text: &str, _tools: Option<&Value>) -> Result<Vec<ToolCall>, Error> {
    // _tool_call_regex = \[(\w+)\((.*?)\)\]
    let (fname, args_str) =
      find_pythonic_call(text).ok_or_else(|| err("pythonic: No function provided."))?;
    let mut arguments = serde_json::Map::new();
    for (k, v) in parse_kw_args(&args_str)? {
      arguments.insert(k, literal_eval(&v));
    }
    Ok(obj(&fname, Value::Object(arguments)))
  }
  fn name(&self) -> &'static str {
    "pythonic"
  }
}

fn find_pythonic_call(text: &str) -> Option<(String, String)> {
  // Equivalent of \[(\w+)\((.*?)\)\] with DOTALL, first match.
  let bytes = text.as_bytes();
  let mut i = 0;
  while i < bytes.len() {
    if bytes[i] == b'[' {
      let mut j = i + 1;
      let name_start = j;
      while j < bytes.len() && (bytes[j].is_ascii_alphanumeric() || bytes[j] == b'_') {
        j += 1;
      }
      if j > name_start && j < bytes.len() && bytes[j] == b'(' {
        let name = text[name_start..j].to_owned();
        // non-greedy up to `)]`
        let rest = &text[j + 1..];
        if let Some(close) = rest.find(")]") {
          return Some((name, rest[..close].to_owned()));
        }
      }
    }
    i += 1;
  }
  None
}

/// Parse `key=value, key="value"` pairs (Python `_tool_args_regex`
/// `(\w+)=(?:"([^"]*)"|([^,]+))(?:,\s*|$)`, `findall`).
///
/// All slicing is on offsets measured against the *original* `rest` slice
/// (the leading-whitespace skip is folded into the cursor), so a non-ASCII
/// value after spaces (`city=  "é"`) can never slice a UTF-8 char boundary.
/// Malformed input returns a tokenizer parse [`Error`] rather than panicking.
fn parse_kw_args(s: &str) -> Result<Vec<(String, String)>, Error> {
  let mut out = Vec::new();
  let mut rest = s.trim();
  while !rest.is_empty() {
    let eq = match rest.find('=') {
      Some(e) => e,
      None => break,
    };
    // `rest[..eq]` ends just before an ASCII `=`, always a char boundary.
    let key = rest[..eq].trim().to_owned();
    // Absolute byte offset of the value start within `rest`, after the `=`
    // and any whitespace. `eq + 1` is past the 1-byte `=` (char boundary);
    // the trimmed prefix length is added back so every later index into
    // `rest` is computed from `rest` itself, never from a re-sliced `after`.
    let val_start = {
      let after = &rest[eq + 1..];
      eq + 1 + (after.len() - after.trim_start().len())
    };
    let value_region = &rest[val_start..];
    let (val, consumed) = if let Some(stripped) = value_region.strip_prefix('"') {
      // Quoted: `"([^"]*)"` — inner up to the next `"`.
      match stripped.find('"') {
        // val_start + 1 (open quote) + end (inner len) + 1 (close quote).
        Some(end) => (stripped[..end].to_owned(), val_start + 1 + end + 1),
        // Unterminated quote: keep the rest as the value (matches the prior
        // lenient behaviour) and stop — no further char-boundary slicing.
        None => (stripped.to_owned(), rest.len()),
      }
    } else {
      // Unquoted: `[^,]+` — up to the next `,` (or end).
      let end = value_region.find(',').unwrap_or(value_region.len());
      (value_region[..end].trim().to_owned(), val_start + end)
    };
    out.push((key, val));
    if consumed >= rest.len() {
      break;
    }
    // `consumed` is always a char boundary: it is `val_start` (boundary)
    // plus byte lengths of whole matched ASCII-delimited regions. Guard
    // anyway so corrupt offsets surface as an `Error`, never a panic.
    if !rest.is_char_boundary(consumed) {
      return Err(err("pythonic: malformed argument encoding"));
    }
    rest = rest[consumed..]
      .trim_start()
      .trim_start_matches(',')
      .trim_start();
  }
  Ok(out)
}

// ----------------------------------------------------------------------------
// mistral: name[ARGS]{json}
// ----------------------------------------------------------------------------

/// `mistral` — `[TOOL_CALLS]name[ARGS]{json}`.
pub struct Mistral;

impl ToolParser for Mistral {
  fn parse(&self, text: &str, _tools: Option<&Value>) -> Result<Vec<ToolCall>, Error> {
    // \s*(\w+)\[ARGS\]\s*(\{.*\})
    let idx = text
      .find("[ARGS]")
      .ok_or_else(|| err(format!("mistral: Could not parse tool call from: {text}")))?;
    let name = text[..idx].trim().to_owned();
    let after = text[idx + "[ARGS]".len()..].trim_start();
    let brace = after
      .find('{')
      .ok_or_else(|| err("mistral: no json args"))?;
    let json_str = after[brace..].trim_end();
    let args: Value = serde_json::from_str(json_str).map_err(|e| err(format!("mistral: {e}")))?;
    Ok(obj(&name, args))
  }
  fn name(&self) -> &'static str {
    "mistral"
  }
}

// ----------------------------------------------------------------------------
// qwen3_coder: <function=name>...<parameter=p>v</parameter></function>
// ----------------------------------------------------------------------------

/// `qwen3_coder` — XML-style `<function=name><parameter=p>v</parameter></function>`.
pub struct Qwen3Coder;

impl ToolParser for Qwen3Coder {
  fn parse(&self, text: &str, tools: Option<&Value>) -> Result<Vec<ToolCall>, Error> {
    // _function_regex = <function=(.*?)</function>$ (DOTALL, findall->[0])
    let start = text
      .find("<function=")
      .ok_or_else(|| err("qwen3_coder: No function provided."))?;
    let after = &text[start + "<function=".len()..];
    let end = after
      .rfind("</function>")
      .ok_or_else(|| err("qwen3_coder: No function provided."))?;
    let body = &after[..end];
    let gt = body
      .find('>')
      .ok_or_else(|| err("qwen3_coder: malformed function"))?;
    let func_name = body[..gt].to_owned();
    let params_str = &body[gt + 1..];
    let props = tool_properties(tools, &func_name);
    let mut args = serde_json::Map::new();
    for cap in find_all(params_str, "<parameter=", "</parameter>") {
      let pgt = match cap.find('>') {
        Some(p) => p,
        None => continue,
      };
      let pname = cap[..pgt].to_owned();
      let mut pval = cap[pgt + 1..].to_owned();
      if let Some(r) = pval.strip_prefix('\n') {
        pval = r.to_owned();
      }
      if let Some(r) = pval.strip_suffix('\n') {
        pval = r.to_owned();
      }
      args.insert(pname.clone(), convert_param_value(&pval, &pname, props));
    }
    Ok(obj(&func_name, Value::Object(args)))
  }
  fn name(&self) -> &'static str {
    "qwen3_coder"
  }
}

fn convert_param_value(
  v: &str,
  name: &str,
  props: Option<&serde_json::Map<String, Value>>,
) -> Value {
  if v.eq_ignore_ascii_case("null") {
    return Value::Null;
  }
  let Some(props) = props else {
    return Value::String(v.to_owned());
  };
  let Some(schema) = props.get(name) else {
    return Value::String(v.to_owned());
  };
  let ptype = schema
    .get("type")
    .and_then(Value::as_str)
    .unwrap_or("string")
    .trim()
    .to_lowercase();
  const STR: &[&str] = &["string", "str", "text", "varchar", "char", "enum"];
  const BOOL: &[&str] = &["boolean", "bool", "binary"];
  const OBJ: &[&str] = &["object", "array", "arr"];
  if STR.contains(&ptype.as_str()) {
    Value::String(v.to_owned())
  } else if ["int", "uint", "long", "short", "unsigned"]
    .iter()
    .any(|p| ptype.starts_with(p))
  {
    v.trim()
      .parse::<i64>()
      .map(|i| Value::Number(i.into()))
      .unwrap_or_else(|_| Value::String(v.to_owned()))
  } else if ptype.starts_with("num") || ptype.starts_with("float") {
    match v.trim().parse::<f64>() {
      Ok(f) if f.fract() == 0.0 => Value::Number((f as i64).into()),
      Ok(f) => serde_json::Number::from_f64(f)
        .map(Value::Number)
        .unwrap_or(Value::Null),
      Err(_) => Value::String(v.to_owned()),
    }
  } else if BOOL.contains(&ptype.as_str()) {
    Value::Bool(v.trim().eq_ignore_ascii_case("true"))
  } else if OBJ.contains(&ptype.as_str()) || ptype.starts_with("dict") || ptype.starts_with("list")
  {
    serde_json::from_str(v).unwrap_or_else(|_| literal_eval(v))
  } else {
    literal_eval(v)
  }
}

/// Find all substrings between `open` and the next `close` (DOTALL,
/// non-greedy), returning the inner text of each match.
fn find_all(text: &str, open: &str, close: &str) -> Vec<String> {
  let mut out = Vec::new();
  let mut i = 0;
  while let Some(s) = text[i..].find(open) {
    let abs = i + s + open.len();
    if let Some(e) = text[abs..].find(close) {
      out.push(text[abs..abs + e].to_owned());
      i = abs + e + close.len();
    } else {
      break;
    }
  }
  out
}

// ----------------------------------------------------------------------------
// glm47: name<arg_key>k</arg_key><arg_value>v</arg_value>...
// ----------------------------------------------------------------------------

/// `glm47` — `name<arg_key>k</arg_key><arg_value>v</arg_value>` with JSON /
/// plain-text fallbacks.
pub struct Glm47;

impl ToolParser for Glm47 {
  fn parse(&self, text: &str, tools: Option<&Value>) -> Result<Vec<ToolCall>, Error> {
    if let Some(idx) = text.find("<arg_key>") {
      let func_name = text[..idx].trim().to_owned();
      let string_args = string_arg_names(tools, &func_name);
      let mut args = serde_json::Map::new();
      for (k, v) in find_kv_pairs(
        text,
        "<arg_key>",
        "</arg_key>",
        "<arg_value>",
        "</arg_value>",
      ) {
        let key = k.trim().to_owned();
        let val = if string_args.contains(&key) {
          Value::String(v.trim().to_owned())
        } else {
          deserialize(v.trim())
        };
        args.insert(key, val);
      }
      return Ok(obj(&func_name, Value::Object(args)));
    }
    // Fallbacks.
    if let Some(c) = glm_parse_json(text, tools) {
      return Ok(vec![c]);
    }
    if let Some(c) = glm_parse_plain(text, tools) {
      return Ok(vec![c]);
    }
    Ok(vec![ToolCall::new(
      "unknown",
      serde_json::json!({"raw": text.trim()}),
    )])
  }
  fn name(&self) -> &'static str {
    "glm47"
  }
}

fn normalize_arguments(
  func_name: &str,
  arguments: &serde_json::Map<String, Value>,
  tools: Option<&Value>,
) -> serde_json::Map<String, Value> {
  let string_args = string_arg_names(tools, func_name);
  let mut out = serde_json::Map::new();
  for (k, v) in arguments {
    if string_args.contains(k) {
      let coerced = match v {
        Value::String(s) => Value::String(s.clone()),
        other => Value::String(other.to_string()),
      };
      out.insert(k.clone(), coerced);
    } else if let Value::String(s) = v {
      out.insert(k.clone(), deserialize(s));
    } else {
      out.insert(k.clone(), v.clone());
    }
  }
  out
}

fn glm_parse_json(text: &str, tools: Option<&Value>) -> Option<ToolCall> {
  let parsed: Value = serde_json::from_str(text.trim()).ok()?;
  let parsed = match &parsed {
    Value::Array(a) if !a.is_empty() && a[0].is_object() => a[0].clone(),
    _ => parsed,
  };
  let p = parsed.as_object()?;
  let (mut name, mut arguments) = if p.contains_key("name") && p.contains_key("arguments") {
    (p.get("name").cloned(), p.get("arguments").cloned())
  } else if p.contains_key("function") && p.contains_key("arguments") {
    (p.get("function").cloned(), p.get("arguments").cloned())
  } else if let Some(t) = p.get("tool").and_then(Value::as_object) {
    (t.get("name").cloned(), t.get("arguments").cloned())
  } else {
    (None, None)
  };
  if let Some(Value::Object(nm)) = &name {
    if arguments.is_none() {
      arguments = nm.get("arguments").cloned();
    }
    name = nm.get("name").cloned();
  }
  if let Some(Value::String(s)) = &arguments {
    arguments = Some(deserialize(s));
  }
  let name = name.and_then(|n| n.as_str().map(str::to_owned))?;
  match arguments {
    None => Some(ToolCall::new(name, serde_json::json!({}))),
    Some(Value::Object(m)) => {
      let norm = normalize_arguments(&name, &m, tools);
      Some(ToolCall::new(name, Value::Object(norm)))
    }
    _ => None,
  }
}

fn glm_parse_plain(text: &str, tools: Option<&Value>) -> Option<ToolCall> {
  let stripped = text.trim();
  if stripped.is_empty() {
    return None;
  }
  if let Some(nl) = stripped.find('\n') {
    let name = stripped[..nl].trim().to_owned();
    let rest = stripped[nl + 1..].trim();
    if !name.is_empty()
      && !rest.is_empty()
      && let Value::Object(m) = deserialize(rest)
    {
      let norm = normalize_arguments(&name, &m, tools);
      return Some(ToolCall::new(name, Value::Object(norm)));
    }
  }
  let (name, rest) = match stripped.split_once(' ') {
    Some((n, r)) => (n.to_owned(), r.trim().to_owned()),
    None => (stripped.to_owned(), String::new()),
  };
  if name.is_empty() {
    return None;
  }
  if rest.is_empty() {
    return Some(ToolCall::new(name, serde_json::json!({})));
  }
  if let Value::Object(m) = deserialize(&rest) {
    let norm = normalize_arguments(&name, &m, tools);
    return Some(ToolCall::new(name, Value::Object(norm)));
  }
  // key=value pairs
  if rest.contains('=') {
    let mut args = serde_json::Map::new();
    let string_args = string_arg_names(tools, &name);
    let mut ok = true;
    for token in rest.split_whitespace() {
      match token.split_once('=') {
        Some((k, v)) if !k.trim().is_empty() => {
          let key = k.trim().to_owned();
          if string_args.contains(&key) {
            args.insert(key, Value::String(v.to_owned()));
          } else {
            args.insert(key, deserialize(v));
          }
        }
        _ => {
          ok = false;
          break;
        }
      }
    }
    if ok && !args.is_empty() {
      return Some(ToolCall::new(name, Value::Object(args)));
    }
  }
  Some(ToolCall::new(name, serde_json::json!({"raw": rest})))
}

/// Find `(key, value)` pairs delimited by two open/close tag pairs.
fn find_kv_pairs(text: &str, ko: &str, kc: &str, vo: &str, vc: &str) -> Vec<(String, String)> {
  let mut out = Vec::new();
  let mut i = 0;
  while let Some(ks) = text[i..].find(ko) {
    let kabs = i + ks + ko.len();
    let Some(ke) = text[kabs..].find(kc) else {
      break;
    };
    let key = text[kabs..kabs + ke].to_owned();
    let after = kabs + ke + kc.len();
    let Some(vs) = text[after..].find(vo) else {
      break;
    };
    let vabs = after + vs + vo.len();
    let Some(ve) = text[vabs..].find(vc) else {
      break;
    };
    let val = text[vabs..vabs + ve].to_owned();
    out.push((key, val));
    i = vabs + ve + vc.len();
  }
  out
}

// ----------------------------------------------------------------------------
// kimi_k2: <|tool_call_begin|>functions.name:0<|tool_call_argument_begin|>{json}<|tool_call_end|>
// ----------------------------------------------------------------------------

/// `kimi_k2` — `<|tool_call_begin|>functions.name:0<|tool_call_argument_begin|>{json}<|tool_call_end|>`.
pub struct KimiK2;

impl KimiK2 {
  fn parse_single(text: &str) -> Result<ToolCall, Error> {
    let abeg = "<|tool_call_argument_begin|>";
    let abeg_idx = text
      .find(abeg)
      .ok_or_else(|| err("kimi_k2: No tool call found."))?;
    let head = text[..abeg_idx].trim();
    // ^\s*((?:functions\.)?(.+?):\d+)\s*
    let colon = head
      .rfind(':')
      .ok_or_else(|| err("kimi_k2: No tool call found."))?;
    if head[colon + 1..].trim().parse::<u64>().is_err() {
      return Err(err("kimi_k2: No tool call found."));
    }
    let full_id = head.to_owned();
    let base = &head[..colon];
    let func_name = base.strip_prefix("functions.").unwrap_or(base).to_owned();
    let args_part = text[abeg_idx + abeg.len()..].trim();
    let arg = deserialize(args_part);
    Ok(ToolCall {
      name: func_name,
      arguments: arg,
      id: Some(full_id),
    })
  }
}

impl ToolParser for KimiK2 {
  fn parse(&self, text: &str, _tools: Option<&Value>) -> Result<Vec<ToolCall>, Error> {
    let matches = find_all(text, "<|tool_call_begin|>", "<|tool_call_end|>");
    if matches.is_empty() {
      Ok(vec![Self::parse_single(text)?])
    } else {
      matches.iter().map(|m| Self::parse_single(m)).collect()
    }
  }
  fn name(&self) -> &'static str {
    "kimi_k2"
  }
}

// ----------------------------------------------------------------------------
// longcat
// ----------------------------------------------------------------------------

/// `longcat` — `name<longcat_arg_key>k</longcat_arg_key><longcat_arg_value>v</longcat_arg_value>`.
pub struct Longcat;

impl ToolParser for Longcat {
  fn parse(&self, text: &str, tools: Option<&Value>) -> Result<Vec<ToolCall>, Error> {
    let text = text.trim();
    if text.starts_with('{')
      && let Ok(v) = serde_json::from_str::<Value>(text)
    {
      // Python `longcat` returns the raw parsed dict here. We surface its
      // `name` / `arguments` (falling back to the whole object) so callers
      // still get a structured ToolCall.
      let name = v
        .get("name")
        .and_then(Value::as_str)
        .unwrap_or("")
        .to_owned();
      let args = match v.get("arguments") {
        Some(a) => a.clone(),
        None => v,
      };
      return Ok(obj(&name, args));
    }
    let idx = text
      .find("<longcat_arg_key>")
      .ok_or_else(|| err("longcat: no function name"))?;
    let func_name = text[..idx].trim().to_owned();
    let string_args = string_arg_names(tools, &func_name);
    let mut args = serde_json::Map::new();
    for (k, v) in find_kv_pairs(
      text,
      "<longcat_arg_key>",
      "</longcat_arg_key>",
      "<longcat_arg_value>",
      "</longcat_arg_value>",
    ) {
      let key = k.trim().to_owned();
      let val = if string_args.contains(&key) {
        Value::String(v.trim().to_owned())
      } else {
        deserialize(v.trim())
      };
      args.insert(key, val);
    }
    Ok(obj(&func_name, Value::Object(args)))
  }
  fn name(&self) -> &'static str {
    "longcat"
  }
}

// ----------------------------------------------------------------------------
// minimax_m2: <invoke name="n"><parameter name="p">v</parameter></invoke>
// ----------------------------------------------------------------------------

/// `minimax_m2` — `<invoke name="n"><parameter name="p">v</parameter></invoke>`.
pub struct MinimaxM2;

fn extract_name(s: &str) -> String {
  let s = s.trim();
  if (s.starts_with('"') && s.ends_with('"') && s.len() >= 2)
    || (s.starts_with('\'') && s.ends_with('\'') && s.len() >= 2)
  {
    s[1..s.len() - 1].to_owned()
  } else {
    s.to_owned()
  }
}

fn schema_types(schema: &Value) -> Vec<String> {
  let mut types = std::collections::BTreeSet::new();
  if let Some(o) = schema.as_object() {
    match o.get("type") {
      Some(Value::String(s)) => {
        types.insert(s.clone());
      }
      Some(Value::Array(a)) => {
        for t in a {
          if let Some(s) = t.as_str() {
            types.insert(s.to_owned());
          }
        }
      }
      _ => {}
    }
    if let Some(Value::Array(en)) = o.get("enum") {
      for v in en {
        types.insert(
          match v {
            Value::Null => "null",
            Value::Bool(_) => "boolean",
            Value::Number(n) if n.is_i64() || n.is_u64() => "integer",
            Value::Number(_) => "number",
            Value::String(_) => "string",
            Value::Array(_) => "array",
            Value::Object(_) => "object",
          }
          .to_owned(),
        );
      }
    }
    for cf in ["anyOf", "oneOf", "allOf"] {
      if let Some(Value::Array(a)) = o.get(cf) {
        for c in a {
          for t in schema_types(c) {
            types.insert(t);
          }
        }
      }
    }
  }
  if types.is_empty() {
    vec!["string".to_owned()]
  } else {
    types.into_iter().collect()
  }
}

fn convert_with_types(value: &str, ptypes: &[String]) -> Value {
  if value.eq_ignore_ascii_case("null") {
    return Value::Null;
  }
  let norm: Vec<String> = ptypes.iter().map(|t| t.to_lowercase()).collect();
  let lv = value.to_lowercase();
  if norm.iter().any(|t| t == "null") || ["null", "none", "nil"].contains(&lv.as_str()) {
    return Value::Null;
  }
  for pt in [
    "integer", "int", "number", "float", "boolean", "bool", "object", "array", "string", "str",
    "text",
  ] {
    if !norm.iter().any(|t| t == pt) {
      continue;
    }
    match pt {
      "string" | "str" | "text" => return Value::String(value.to_owned()),
      "integer" | "int" => {
        if let Ok(i) = value.parse::<i64>() {
          return Value::Number(i.into());
        }
      }
      "number" | "float" => {
        if let Ok(f) = value.parse::<f64>() {
          return if f.fract() == 0.0 {
            Value::Number((f as i64).into())
          } else {
            serde_json::Number::from_f64(f)
              .map(Value::Number)
              .unwrap_or(Value::Null)
          };
        }
      }
      "boolean" | "bool" => {
        let l = value.trim().to_lowercase();
        if ["true", "1", "yes", "on"].contains(&l.as_str()) {
          return Value::Bool(true);
        }
        if ["false", "0", "no", "off"].contains(&l.as_str()) {
          return Value::Bool(false);
        }
      }
      "object" | "array" => {
        if let Ok(v) = serde_json::from_str::<Value>(value) {
          return v;
        }
      }
      _ => {}
    }
  }
  serde_json::from_str::<Value>(value).unwrap_or_else(|_| Value::String(value.to_owned()))
}

impl ToolParser for MinimaxM2 {
  fn parse(&self, text: &str, tools: Option<&Value>) -> Result<Vec<ToolCall>, Error> {
    let invokes = find_all(text, "<invoke name=", "</invoke>");
    if invokes.is_empty() {
      return Err(err("minimax_m2: No tool call found"));
    }
    let mut calls = Vec::new();
    for inv in &invokes {
      let name_seg = inv.split('>').next().unwrap_or("");
      let function_name = extract_name(name_seg);
      let props = tool_properties(tools, &function_name);
      let mut args = serde_json::Map::new();
      for pm in find_all(inv, "<parameter name=", "</parameter>") {
        let gt = match pm.find('>') {
          Some(g) => g,
          None => continue,
        };
        let pname = extract_name(&pm[..gt]);
        let mut pval = pm[gt + 1..].trim().to_owned();
        if let Some(r) = pval.strip_prefix('\n') {
          pval = r.to_owned();
        }
        if let Some(r) = pval.strip_suffix('\n') {
          pval = r.to_owned();
        }
        let ptypes = props
          .and_then(|p| p.get(&pname))
          .map(schema_types)
          .unwrap_or_else(|| vec!["string".to_owned()]);
        args.insert(pname, convert_with_types(&pval, &ptypes));
      }
      calls.push(ToolCall::new(&function_name, Value::Object(args)));
    }
    Ok(calls)
  }
  fn name(&self) -> &'static str {
    "minimax_m2"
  }
}

// ----------------------------------------------------------------------------
// function_gemma: call:name{k:v,...} with <escape> string markers
// ----------------------------------------------------------------------------

/// `function_gemma` — `call:name{k:v,...}` with `<escape>`-delimited strings.
pub struct FunctionGemma;

impl ToolParser for FunctionGemma {
  fn parse(&self, text: &str, _tools: Option<&Value>) -> Result<Vec<ToolCall>, Error> {
    // call:(\w+)\{(.*?)\}
    let (func_name, mut args_str) =
      gemma_call(text, false).ok_or_else(|| err("function_gemma: No function provided."))?;
    let mut arguments = serde_json::Map::new();
    let escape = "<escape>";
    while !args_str.is_empty() {
      let split = match args_str.find(':') {
        Some(s) => s,
        None => break,
      };
      let key = args_str[..split].to_owned();
      args_str = args_str[split + 1..].to_owned();
      if let Some(rest) = args_str.strip_prefix(escape)
        && let Some(end) = rest.find(escape)
      {
        arguments.insert(key, Value::String(rest[..end].to_owned()));
        // Python: `args_str = args_str[split + len(escape) + 1:]` — the `+1`
        // skips the trailing `,`. `end + escape.len()` is a char boundary
        // (just past the ASCII `<escape>`); the extra byte is only valid if
        // it is the 1-byte ASCII `,`. A non-ASCII char there must not slice
        // mid-UTF-8 — surface a parse `Error` instead of panicking.
        let after_escape = end + escape.len();
        let consumed = after_escape + 1;
        args_str = if consumed >= rest.len() {
          String::new()
        } else if rest.is_char_boundary(consumed) {
          rest[consumed..].to_owned()
        } else {
          return Err(err("function_gemma: malformed argument encoding"));
        };
        continue;
      }
      let split = args_str.find(',').unwrap_or(args_str.len());
      let value = args_str[..split].to_owned();
      args_str = if split < args_str.len() {
        args_str[(split + 1).min(args_str.len())..].to_owned()
      } else {
        String::new()
      };
      let v =
        serde_json::from_str::<Value>(&value).unwrap_or_else(|_| Value::String(value.clone()));
      arguments.insert(key, v);
    }
    Ok(obj(&func_name, Value::Object(arguments)))
  }
  fn name(&self) -> &'static str {
    "function_gemma"
  }
}

/// Find `call:name{...}` — non-greedy `{.*?}` when `balanced` is false.
fn gemma_call(text: &str, _balanced: bool) -> Option<(String, String)> {
  let s = text.find("call:")?;
  let after = &text[s + 5..];
  let mut j = 0;
  let bytes = after.as_bytes();
  while j < bytes.len()
    && (bytes[j].is_ascii_alphanumeric() || bytes[j] == b'_' || bytes[j] == b'-')
  {
    j += 1;
  }
  if j == 0 || j >= bytes.len() || bytes[j] != b'{' {
    return None;
  }
  let name = after[..j].to_owned();
  let rest = &after[j + 1..];
  let close = rest.find('}')?;
  Some((name, rest[..close].to_owned()))
}

// ----------------------------------------------------------------------------
// gemma4: call:name{bare_keys: <|"|>str<|"|>, ...} with balanced braces
// ----------------------------------------------------------------------------

/// `gemma4` — `call:name{key: <|"|>string<|"|>, n: 2}` with bare keys, `<|"|>`
/// string delimiters and balanced nested braces.
pub struct Gemma4;

impl ToolParser for Gemma4 {
  fn parse(&self, text: &str, _tools: Option<&Value>) -> Result<Vec<ToolCall>, Error> {
    let calls = gemma4_calls(text);
    if calls.is_empty() {
      return Err(err("gemma4: No function provided."));
    }
    let mut out = Vec::new();
    for (name, args_str) in calls {
      let json_str = gemma4_args_to_json(&args_str);
      let arguments: Value =
        serde_json::from_str(&json_str).map_err(|e| err(format!("gemma4: {e}")))?;
      out.push(ToolCall::new(&name, arguments));
    }
    Ok(out)
  }
  fn name(&self) -> &'static str {
    "gemma4"
  }
}

/// Find all `call:name{...}` with balanced braces, ignoring braces inside
/// `<|"|>...<|"|>` string literals.
fn gemma4_calls(text: &str) -> Vec<(String, String)> {
  let mut out = Vec::new();
  let mut i = 0;
  while let Some(s) = text[i..].find("call:") {
    let abs = i + s + 5;
    let after = &text[abs..];
    let mut j = 0;
    let b = after.as_bytes();
    while j < b.len() && (b[j].is_ascii_alphanumeric() || b[j] == b'_' || b[j] == b'-') {
      j += 1;
    }
    if j == 0 || j >= b.len() || b[j] != b'{' {
      i = abs;
      continue;
    }
    let name = after[..j].to_owned();
    let body = &after[j..];
    if let Some(end) = balanced_brace_end(body) {
      out.push((name, body[..=end].to_owned()));
      i = abs + j + end + 1;
    } else {
      i = abs + j;
    }
  }
  out
}

/// Given text starting with `{`, return the index of the matching `}`,
/// skipping `<|"|>...<|"|>` literals.
fn balanced_brace_end(s: &str) -> Option<usize> {
  let bytes = s.as_bytes();
  if bytes.first() != Some(&b'{') {
    return None;
  }
  let lit = "<|\"|>";
  let mut depth = 0usize;
  let mut idx = 0;
  while idx < s.len() {
    if s[idx..].starts_with(lit) {
      // skip to closing literal
      if let Some(close) = s[idx + lit.len()..].find(lit) {
        idx = idx + lit.len() + close + lit.len();
        continue;
      } else {
        return None;
      }
    }
    match bytes[idx] {
      b'{' => depth += 1,
      b'}' => {
        depth -= 1;
        if depth == 0 {
          return Some(idx);
        }
      }
      _ => {}
    }
    // Advance by the full UTF-8 width of the char at `idx`, not a single
    // byte: a non-ASCII char inside the braces would otherwise leave `idx`
    // mid-codepoint and panic on the next `s[idx..]` slice. ASCII (the only
    // structural chars: `{` `}` and the literal) is unaffected (width 1).
    idx += utf8_char_width(bytes[idx]);
  }
  None
}

/// UTF-8 encoded width (1..=4) of the char whose first byte is `b`. A stray
/// continuation byte yields 1 so the scan still makes progress instead of
/// looping or panicking on malformed input.
#[inline]
fn utf8_char_width(b: u8) -> usize {
  match b {
    0x00..=0x7F => 1,
    0xC0..=0xDF => 2,
    0xE0..=0xEF => 3,
    0xF0..=0xF7 => 4,
    _ => 1,
  }
}

fn gemma4_args_to_json(text: &str) -> String {
  // Extract <|"|>...<|"|> strings into placeholders.
  let lit = "<|\"|>";
  let mut strings: Vec<String> = Vec::new();
  let mut result = String::new();
  let mut i = 0;
  while i < text.len() {
    if text[i..].starts_with(lit)
      && let Some(close) = text[i + lit.len()..].find(lit)
    {
      let inner = &text[i + lit.len()..i + lit.len() + close];
      result.push('\u{0}');
      result.push_str(&strings.len().to_string());
      result.push('\u{0}');
      strings.push(inner.to_owned());
      i = i + lit.len() + close + lit.len();
      continue;
    }
    let ch = text[i..].chars().next().unwrap();
    result.push(ch);
    i += ch.len_utf8();
  }
  // Quote bare keys: (?<=[{,])(\w+):  -> "\1":
  let mut quoted = String::new();
  let rb = result.as_bytes();
  let mut k = 0;
  while k < result.len() {
    let c = rb[k];
    quoted.push(c as char);
    if c == b'{' || c == b',' {
      // read following \w+ then ':'
      let mut m = k + 1;
      while m < rb.len() && (rb[m].is_ascii_alphanumeric() || rb[m] == b'_') {
        m += 1;
      }
      if m > k + 1 && m < rb.len() && rb[m] == b':' {
        quoted.push('"');
        quoted.push_str(&result[k + 1..m]);
        quoted.push('"');
        quoted.push(':');
        k = m + 1;
        continue;
      }
    }
    k += 1;
  }
  // Restore captured strings as JSON-escaped strings.
  for (idx, sv) in strings.iter().enumerate() {
    let placeholder = format!("\u{0}{idx}\u{0}");
    let json = serde_json::to_string(sv).unwrap_or_else(|_| "\"\"".into());
    quoted = quoted.replace(&placeholder, &json);
  }
  quoted
}

// ----------------------------------------------------------------------------
// Selection
// ----------------------------------------------------------------------------

/// Build a boxed parser by Python module name. Returns `None` for unknown
/// names (mirrors importlib failing silently into "no parser").
pub fn parser_by_name(name: &str) -> Option<Box<dyn ToolParser>> {
  Some(match name {
    "json_tools" => Box::new(JsonTools),
    "pythonic" => Box::new(Pythonic),
    "mistral" => Box::new(Mistral),
    "qwen3_coder" => Box::new(Qwen3Coder),
    "glm47" => Box::new(Glm47),
    "kimi_k2" => Box::new(KimiK2),
    "longcat" => Box::new(Longcat),
    "minimax_m2" => Box::new(MinimaxM2),
    "function_gemma" => Box::new(FunctionGemma),
    "gemma4" => Box::new(Gemma4),
    _ => return None,
  })
}

/// Auto-infer a tool-parser name from a chat-template string. Direct port of
/// Python `_infer_tool_parser` (`tokenizer_utils.py` ~548), order-preserving.
///
/// The selection chain is the `cargo xtask-codegen`-generated
/// `TOOL_PARSER_SELECT` table (sourced from
/// `mlxrs/data/tokenizer/tool_parsers.toml`, mlx-lm df1d3f3),
/// walked in declaration order: the first rule whose `all` substrings are all
/// present *and* (`any_of` empty or one present) wins — semantically
/// identical to the Python if/elif chain.
pub fn infer_tool_parser(chat_template: Option<&str>) -> Option<&'static str> {
  let ct = chat_template?;
  for rule in TOOL_PARSER_SELECT {
    let all_ok = rule.all.iter().all(|s| ct.contains(s));
    let any_ok = rule.any_of.is_empty() || rule.any_of.iter().any(|s| ct.contains(s));
    if all_ok && any_ok {
      return Some(rule.name);
    }
  }
  None
}
