//! Tokenizer codegen — formerly `mlxrs/build.rs`.
//!
//! Regenerates the committed artifacts from the checked-in source-of-truth
//! data under `mlxrs/data/tokenizer/` (plus the deterministic GPT-2
//! `bytes_to_unicode` algorithm). Output is byte-identical to what the old
//! `mlxrs/build.rs` emitted into `OUT_DIR`; only the *location* moved
//! (committed source instead of a build-script side effect) so a normal
//! `mlxrs` build never compiles `tokenizers` / `serde_json` / `toml`.
//!
//! Two modes (the subcommand needs the `codegen` feature; use the
//! `cargo xtask-codegen` alias = `cargo run -p xtask --features codegen --
//! codegen`):
//!
//! - `cargo xtask-codegen` — write every artifact to its committed path.
//! - `cargo xtask-codegen --check` — regenerate every artifact in-memory
//!   and compare it byte-for-byte against the committed file on disk; no
//!   temp dir and no writes. Non-zero exit on any drift.

use std::{
  fmt::Write as _,
  fs,
  path::{Path, PathBuf},
  process::ExitCode,
};

/// One regenerated artifact: its committed path (relative to the workspace
/// root) and its freshly generated bytes.
struct Artifact {
  /// Path relative to the workspace root, e.g.
  /// `mlxrs/src/tokenizer/generated.rs`.
  rel: &'static str,
  /// The regenerated content.
  bytes: Vec<u8>,
}

/// `cargo xtask-codegen [--check]` entry point.
pub fn run(check: bool) -> ExitCode {
  let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
  let workspace_root = manifest_dir
    .parent()
    .expect("xtask is a workspace member")
    .to_path_buf();
  let data = workspace_root.join("mlxrs/data/tokenizer");

  let artifacts = vec![
    Artifact {
      rel: "mlxrs/src/tokenizer/generated.rs",
      // Pipe through `rustfmt` with the workspace `rustfmt.toml` so the
      // committed file is already fmt-clean (it is normal compiled source
      // now, so `cargo fmt --all -- --check` sees it). The table *content*
      // is unaffected — only whitespace/layout.
      bytes: rustfmt(&generated_rs(&data), &workspace_root).into_bytes(),
    },
    Artifact {
      rel: "mlxrs/tests/fixtures/tokenizer.json",
      bytes: tokenizer_fixture_json(),
    },
    Artifact {
      rel: "mlxrs/tests/fixtures/tokenizer_config.json",
      bytes: tokenizer_config_json(),
    },
  ];

  if check {
    let mut drift = false;
    for a in &artifacts {
      let committed = workspace_root.join(a.rel);
      match fs::read(&committed) {
        Ok(existing) if existing == a.bytes => {
          eprintln!("ok      {}", a.rel);
        }
        Ok(_) => {
          eprintln!(
            "DRIFT   {} (committed file differs from a fresh regen)",
            a.rel
          );
          drift = true;
        }
        Err(e) => {
          eprintln!("MISSING {} ({e})", a.rel);
          drift = true;
        }
      }
    }
    if drift {
      eprintln!();
      eprintln!("codegen --check FAILED: run `cargo xtask-codegen` and commit the result.");
      return ExitCode::FAILURE;
    }
    eprintln!();
    eprintln!("codegen --check OK: all committed artifacts match the data source-of-truth.");
    ExitCode::SUCCESS
  } else {
    for a in &artifacts {
      let dst = workspace_root.join(a.rel);
      if let Some(parent) = dst.parent() {
        fs::create_dir_all(parent).expect("create artifact parent dir");
      }
      fs::write(&dst, &a.bytes).expect("write artifact");
      eprintln!("wrote   {}", a.rel);
    }
    ExitCode::SUCCESS
  }
}

/// Build the single committed `mlxrs/src/tokenizer/generated.rs` containing
/// every Rust table the tokenizer source modules consume.
fn generated_rs(data: &Path) -> String {
  let mut s = String::new();
  s.push_str(
    "//! @generated by `cargo xtask-codegen` from mlxrs/data/tokenizer/ \
     (mlx-lm df1d3f3). DO NOT EDIT.\n\
     //!\n\
     //! Regenerate with `cargo xtask-codegen`; `cargo xtask-codegen --check` \
     is the\n\
     //! drift guard. Source-of-truth: the files under \
     `mlxrs/data/tokenizer/`\n\
     //! plus the deterministic GPT-2 `bytes_to_unicode` algorithm.\n\
     //!\n\
     //! `dead_code` is allowed because this module carries every codegen\n\
     //! table but a given feature subset consumes only some of them.\n\
     #![allow(missing_docs, dead_code)]\n\n",
  );

  emit_byte_decoder(&mut s);
  s.push('\n');
  emit_bpe_space_matches(&mut s, data);
  s.push('\n');
  emit_tool_parser_table(&mut s, data);
  s.push('\n');
  emit_deepseek_v32_template(&mut s, data);

  s
}

/// Run `rustfmt` over `src` using the workspace `rustfmt.toml` (2-space,
/// crate-granularity imports, …) so the committed `generated.rs` is already
/// fmt-clean. Returns the formatted source; panics if `rustfmt` is missing
/// or rejects the input (a regression we want loud, not silent).
fn rustfmt(src: &str, workspace_root: &Path) -> String {
  use std::{
    io::Write as _,
    process::{Command, Stdio},
  };

  let mut child = Command::new("rustfmt")
    .arg("--edition")
    .arg("2024")
    .arg("--config-path")
    .arg(workspace_root)
    .stdin(Stdio::piped())
    .stdout(Stdio::piped())
    .stderr(Stdio::piped())
    .spawn()
    .expect("spawn rustfmt (is it on PATH?)");
  child
    .stdin
    .take()
    .expect("rustfmt stdin")
    .write_all(src.as_bytes())
    .expect("write to rustfmt stdin");
  let out = child.wait_with_output().expect("wait for rustfmt");
  assert!(
    out.status.success(),
    "rustfmt failed: {}",
    String::from_utf8_lossy(&out.stderr)
  );
  String::from_utf8(out.stdout).expect("rustfmt emitted non-UTF8")
}

/// **A. GPT-2 byte decoder (algorithmic).** Computes the deterministic
/// `bytes_to_unicode` inverse map and emits a sorted
/// `pub(crate) static BYTE_DECODER: &[(char, u8)]`.
///
/// Algorithm (provenance: <https://github.com/openai/gpt-2/blob/master/src/encoder.py>,
/// mirrored by mlx-lm df1d3f3 `mlx_lm/tokenizer_utils.py` BPE byte table):
/// the printable ranges `'!'..='~'`, `'\u{A1}'..='\u{AC}'`,
/// `'\u{AE}'..='\u{FF}'` map to themselves; every other byte `n` in `0..256`
/// maps to the codepoint `256 + k` where `k` counts the non-printable bytes
/// seen so far. The decoder is the inverse: unicode char -> raw byte.
fn emit_byte_decoder(out: &mut String) {
  let printable: [(u32, u32); 3] = [
    ('!' as u32, '~' as u32),
    ('\u{A1}' as u32, '\u{AC}' as u32),
    ('\u{AE}' as u32, '\u{FF}' as u32),
  ];
  let is_printable = |b: u32| printable.iter().any(|&(lo, hi)| b >= lo && b <= hi);

  let mut pairs: Vec<(u32, u8)> = Vec::with_capacity(256);
  let mut n: u32 = 0;
  for b in 0u32..256 {
    let cp = if is_printable(b) {
      b
    } else {
      let c = 256 + n;
      n += 1;
      c
    };
    pairs.push((cp, b as u8));
  }
  pairs.sort_by_key(|&(cp, _)| cp);

  out.push_str(
    "// GPT-2 bytes_to_unicode inverse (char -> byte), sorted by char for\n\
     // binary search. Provenance: openai/gpt-2 encoder.py / mlx-lm df1d3f3.\n\
     pub(crate) static BYTE_DECODER: &[(char, u8)] = &[\n",
  );
  for (cp, b) in &pairs {
    let c = char::from_u32(*cp).expect("valid codepoint");
    writeln!(out, "  ({:?}, {}),", c, b).unwrap();
  }
  out.push_str("];\n");
}

/// **B (bpe_space_matches.toml).** Emits
/// `pub(crate) static BPE_SPACE_MATCHES: &[&str]`.
fn emit_bpe_space_matches(out: &mut String, data: &Path) {
  let src =
    fs::read_to_string(data.join("bpe_space_matches.toml")).expect("read bpe_space_matches.toml");
  let doc: toml::Value = src.parse().expect("parse bpe_space_matches.toml");
  let arr = doc
    .get("matches")
    .and_then(toml::Value::as_array)
    .expect("bpe_space_matches.toml: `matches` array");

  out.push_str(
    "// Source: mlxrs/data/tokenizer/bpe_space_matches.toml (mlx-lm df1d3f3).\n\
     pub(crate) static BPE_SPACE_MATCHES: &[&str] = &[\n",
  );
  for v in arr {
    let s = v
      .as_str()
      .expect("bpe_space_matches entry must be a string");
    writeln!(out, "  {:?},", s).unwrap();
  }
  out.push_str("];\n");
}

/// **B (tool_parsers.toml).** Emits the constant marker + ordered selection
/// dispatch table consumed by `tools.rs`. Parser *logic* stays in Rust;
/// only the literal markers / selection substrings live here.
fn emit_tool_parser_table(out: &mut String, data: &Path) {
  let src = fs::read_to_string(data.join("tool_parsers.toml")).expect("read tool_parsers.toml");
  let doc: toml::Value = src.parse().expect("parse tool_parsers.toml");
  let parsers = doc
    .get("parser")
    .and_then(toml::Value::as_array)
    .expect("tool_parsers.toml: `parser` array");

  out.push_str(
    "// Source: mlxrs/data/tokenizer/tool_parsers.toml (mlx-lm df1d3f3).\n\n\
     /// One entry per tool parser: stable name + `tool_call_start` /\n\
     /// `tool_call_end` delimiters.\n\
     pub(crate) struct ToolParserMarkers {\n\
     \x20\x20pub name: &'static str,\n\
     \x20\x20pub start: &'static str,\n\
     \x20\x20pub end: &'static str,\n\
     }\n\n\
     /// Ordered `_infer_tool_parser` selection rule (mirrors the Python\n\
     /// if/elif chain). A rule fires when every `all` substring is present\n\
     /// AND (`any_of` empty OR at least one `any_of` substring is present).\n\
     pub(crate) struct ToolParserSelect {\n\
     \x20\x20pub name: &'static str,\n\
     \x20\x20pub all: &'static [&'static str],\n\
     \x20\x20pub any_of: &'static [&'static str],\n\
     }\n\n\
     pub(crate) static TOOL_PARSER_MARKERS: &[ToolParserMarkers] = &[\n",
  );

  let mut select = String::from("pub(crate) static TOOL_PARSER_SELECT: &[ToolParserSelect] = &[\n");

  for p in parsers {
    let name = p.get("name").and_then(toml::Value::as_str).expect("name");
    let start = p
      .get("tool_call_start")
      .and_then(toml::Value::as_str)
      .expect("tool_call_start");
    let end = p
      .get("tool_call_end")
      .and_then(toml::Value::as_str)
      .expect("tool_call_end");
    writeln!(
      out,
      "  ToolParserMarkers {{ name: {:?}, start: {:?}, end: {:?} }},",
      name, start, end
    )
    .unwrap();

    let sel = p.get("select").expect("select table");
    let to_arr = |k: &str| -> String {
      let items = sel
        .get(k)
        .and_then(toml::Value::as_array)
        .map(|a| {
          a.iter()
            .map(|v| format!("{:?}", v.as_str().expect("select string")))
            .collect::<Vec<_>>()
            .join(", ")
        })
        .unwrap_or_default();
      format!("&[{items}]")
    };
    writeln!(
      select,
      "  ToolParserSelect {{ name: {:?}, all: {}, any_of: {} }},",
      name,
      to_arr("all"),
      to_arr("any_of")
    )
    .unwrap();
  }
  out.push_str("];\n\n");
  select.push_str("];\n");
  out.push_str(&select);
}

/// **B (chat_template_overrides/deepseek_v32.jinja).** Embeds the literal
/// `TOOLS_SYSTEM_TEMPLATE` text (byte-exact) as a raw string literal so
/// `chat.rs` can consume it without an `include_str!`/`OUT_DIR` indirection.
/// The deepseek_v32 *transform logic* stays in Rust (`chat.rs`).
///
/// Provenance: mlx-lm df1d3f3 `mlx_lm/chat_templates/deepseek_v32.py`
/// `TOOLS_SYSTEM_TEMPLATE` (placeholders rewritten to the Rust port's
/// `{dsml}` / `{think_start}` / `{think_end}` / `{tool_schemas}`).
fn emit_deepseek_v32_template(out: &mut String, data: &Path) {
  let text = fs::read_to_string(data.join("chat_template_overrides/deepseek_v32.jinja"))
    .expect("read deepseek_v32.jinja");
  // Pick a `#` fence wider than any run of `"#` in the payload so the raw
  // string literal is unambiguous regardless of template content.
  let mut hashes = 1usize;
  loop {
    let close = format!("\"{}", "#".repeat(hashes));
    if !text.contains(&close) {
      break;
    }
    hashes += 1;
  }
  let fence = "#".repeat(hashes);
  out.push_str(
    "// Source: mlxrs/data/tokenizer/chat_template_overrides/deepseek_v32.jinja\n\
     // (mlx-lm df1d3f3). Byte-exact embed; substitution pipeline stays in chat.rs.\n",
  );
  writeln!(
    out,
    "pub(crate) static DEEPSEEK_V32_TEMPLATE: &str = r{fence}\"{text}\"{fence};"
  )
  .unwrap();
}

/// The test fixture `tokenizer.json`. Built via the `tokenizers` builder
/// APIs so the emitted JSON is schema-correct by construction (the same
/// crate parses it back at runtime).
fn tokenizer_fixture_json() -> Vec<u8> {
  use tokenizers::{
    AddedToken, Tokenizer, models::wordlevel::WordLevel, pre_tokenizers::whitespace::Whitespace,
  };

  let model = WordLevel::builder()
    .vocab(
      [
        ("<unk>", 0u32),
        ("<s>", 1),
        ("</s>", 2),
        ("hello", 3),
        ("world", 4),
        ("the", 5),
        ("quick", 6),
        ("brown", 7),
        ("fox", 8),
        ("<think>", 9),
        ("</think>", 10),
      ]
      .iter()
      .map(|(k, v)| ((*k).to_string(), *v))
      .collect(),
    )
    .unk_token("<unk>".to_string())
    .build()
    .expect("WordLevel build");

  let mut tokenizer = Tokenizer::new(model);
  tokenizer.with_pre_tokenizer(Some(Whitespace {}));
  tokenizer
    .add_special_tokens([
      AddedToken::from("<unk>", true).special(true),
      AddedToken::from("<s>", true).special(true),
      AddedToken::from("</s>", true).special(true),
    ])
    .expect("add_special_tokens");

  tokenizer
    .to_string(true)
    .expect("serialize tokenizer")
    .into_bytes()
}

/// The matching `tokenizer_config.json`, built with typed
/// `serde_json::json!` (no hand-authored JSON blob). Chat template stays
/// byte-identical to the prior test constant.
fn tokenizer_config_json() -> Vec<u8> {
  use serde_json::json;

  let chat_template = "{{ bos_token }}{% for m in messages %}{{ '<|' + m['role'] + '|>' }}{{ m['content'] }}{% endfor %}{% if tools %}{% for t in tools %}<tool>{{ t['function']['name'] }}</tool>{% endfor %}{% endif %}{% if add_generation_prompt %}<|assistant|>{% endif %}";

  let config = json!({
    "bos_token": "<s>",
    "eos_token": "</s>",
    "unk_token": "<unk>",
    "clean_up_tokenization_spaces": false,
    "chat_template": chat_template,
  });
  serde_json::to_string_pretty(&config)
    .expect("serialize tokenizer_config")
    .into_bytes()
}
